feat: add CredibleAccountProofVerifier to the CredibleAccountValidator
etherspot/etherspot-prime-contracts pull request #88
Opened 2024-09-25 20:31 UTC by kanthgithub

## Description

-

## Motivation and Context

-

## How Has This Been Tested?

-
-
-

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-09-25 20:54 UTC, lbw33 commented on .env.example
I wouldn't have the CREDIBLE_ACCOUNT_PROOF_VERIFIER here. It's not a private env variable and were passing it into the constructor in the contract so it would be exposed any way.

2024-09-25 20:54 UTC, lbw33 commented on script/CredibleAccountValidator.s.sol
I would just pass this into the constructor as a standard variable here without accessing via env.

2024-09-25 21:30 UTC, lbw33 requested changes

2024-09-25 21:30 UTC, lbw33 commented on src/modular-etherspot-wallet/proof/CredibleAccountProofVerifier.sol
I would rename this `ProofVerifier` to decouple it from the `CredibleAccount` module

2024-09-25 21:30 UTC, lbw33 commented on .env.example
I wouldn't have the `CREDIBLE_ACCOUNT_PROOF_VERIFIER` here. It's not a private env variable and were passing it into the `constructor` in the contract so it would be exposed any way.

2024-09-25 21:30 UTC, lbw33 commented on script/CredibleAccountValidator.s.sol
I would just pass this into the `constructor` as a standard variable here without accessing via env.

2024-09-26 08:49 UTC, kanthgithub commented on .env.example
updated

2024-09-26 08:49 UTC, kanthgithub commented on script/CredibleAccountValidator.s.sol
updated

2024-09-26 09:02 UTC, lbw33 approved these changes

2024-09-26 09:11 UTC, merged